[package]
name = "scryer-prolog"
version = "0.8.94"
authors = ["Mark Thom <markjordanthom@gmail.com>"]
repository = "https://github.com/mthom/scryer-prolog"
description = "A modern Prolog implementation written mostly in Rust."
license = "BSD-3-Clause"

[dependencies]
cfg-if = "0.1.7"
dirs = "2.0.2"
downcast = "0.10.0"
indexmap = "1.0.2"
ordered-float = "0.5.0"
prolog_parser = "0.8.29"
ref_thread_local = "0.0.0"
rug = "1.4.0"
rustyline = "5.0.3"

[dependencies.termion]
version = "1.4.0"
