[package]
name = "scryer-prolog"
version = "0.8.115"
authors = ["Mark Thom <markjordanthom@gmail.com>"]
build = "build.rs"
repository = "https://github.com/mthom/scryer-prolog"
description = "A modern Prolog implementation written mostly in Rust."
license = "BSD-3-Clause"
edition = "2018"

[build-dependencies]
indexmap = "1.0.2"

[dependencies]
dirs = "2.0.2"
downcast = "0.10.0"
indexmap = "1.0.2"
lazy_static = "1.4.0"
libc = "0.2.62"
nix = "0.15.0"
ordered-float = "0.5.0"
prolog_parser = "0.8.33"
ref_thread_local = "0.0.0"
rug = "1.4.0"
rustyline = "5.0.3"

[dependencies.termion]
version = "1.4.0"
