[package]
name = "scryer-prolog"
version = "0.8.14"
authors = ["Mark Thom <markjordanthom@gmail.com>"]
repository = "https://github.com/mthom/scryer-prolog"
description = "A modern Prolog implementation written mostly in Rust."
license = "BSD-3-Clause"

[features]
default = ["readline_rs_compat"]

[dependencies]
cfg-if = "0.1.7"
downcast = "0.9.1"
num = "0.2"
ordered-float = "0.5.0"
prolog_parser = "0.8.1"
readline_rs_compat = { version = "0.1.5", optional = true }

[dependencies.termion]
version = "1.4.0"